env:
  browser: true
  es2021: true
  jest: true
extends:
  - mta
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
globals:
  BodyInit: true
  HeadersInit: true
  RequestInit: true
